config/routes.rb
IBDATA::Application.routes.draw do

   resources :ib_contracts
   resources :historical, only: ['show', 'index']
   match 'ibdata/option_data' => 'ibdata#option_data'
   match 'ibdata/historical_data' => 'ibdata#historical_data'
   match 'ibdata/historical_data_for_all_contracts' => 'ibdata#historical_data_for_all_contracts'
   root :to => 'ib_contracts#index'

end

app/models/ib_bar.rb
class IbBar < ActiveRecord::Base
  belongs_to :ib_contract  
end

app/models/ib_contract.rb
class IbContract < ActiveRecord::Base  
	has_many :ib_bars
	attr_accessible :con_id, :sec_type, :strike, :currency, :sec_id_type, :sec_id, :legs_description, :symbol, :local_symbol, :multiplier, :expiry, :exchange, :primary_exchange, :include_expired, :right, :type 
end

app/models/unique_client_id.rb
class UniqueClientId < ActiveRecord::Base
  attr_accessible :client_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/historical_controller.rb
class HistoricalController < ApplicationController
  def show
    @contract = IbContract.find(params[:id])
  end	

  def index
  	@contracts = IbContract.all
  end	
end

app/controllers/ib_contracts_controller.rb
class IbContractsController < ApplicationController
	def index
	  @contracts = IbContract.all 	
	end	

	def new
      @contract = IbContract.new
	end	

	def create
	  @contract = IbContract.new(params[:ib_contract]) 
	  if @contract.save!
	  	redirect_to ib_contracts_path, flash[:notice] => 'Contract created successfully'
	  else
	    render new_ib_contract_path, flash[:error] => 'There is an error while creating contract'
	  end  	
    end	

    def edit
      @contract = IbContract.find(params[:id])	
    end	

    def update
      @contract = IbContract.find(params[:id])
      if @contract.update_attributes(params[:ib_contract])	
        redirect_to ib_contracts_path, flash[:notice] => 'Contract updated successfully'
      else
      	render edit_ib_contract , flash[:error] => 'There is an error while updating contract'
      end	
    end	

    def destroy
      contract = IbContract.find(params[:id])
      if contract.destroy
      	redirect_to ib_contracts_path, flash[:notice] => 'Contract deleted successfully'
      else
      	redirect_to ib_contracts_path, flash[:error] => 'Contract not deleted successfully'
      end	
    end	
end

app/controllers/ibdata_controller.rb
class IbdataController < ApplicationController
    
    def index
      
    end 

    def historical_data
      hash = prepare_contract params[:id]	
      fetch_historical_data hash
      redirect_to historical_path(params[:id])
    end

    def historical_data_for_all_contracts
      contract_ids = IbContract.all.map(&:id)
      contract_ids.each do |contract_id, index|
      	hash = prepare_contract contract_id
        fetch_historical_data hash
      end
      redirect_to historical_index_path
    end
    
    def prepare_contract contract_id
      contract = IbContract.find(contract_id)
      hash = {}
      contract.instance_variables.each {|var| hash[var.to_s.delete("@")] = contract.instance_variable_get(var) }
      hash = hash['attributes'].delete_if{ |k, v| v.nil? || v == '' || k == 'created_at'|| k == 'updated_at' }	
      hash['sec_type'] = hash['sec_type'].to_sym
      hash['currency'] = hash['currency'].upcase 
      hash
    end	

    def option_data
    	@market = {1 => IB::Symbols::Options[:aapl95]}

		# First, connect to IB TWS. Arbitrary :client_id is used to identify your script
		ib = IB::Connection.new :client_id => 1112 #, :port => 7496 # TWS

		## Subscribe to TWS alerts/errors
		ib.subscribe(:Alert) { |msg| puts msg.to_human }

		# Subscribe to Ticker... events.  The code passed in the block will be executed when
		# any message of that type is received, with the received message as its argument.
		# In this case, we just print out the tick.
		#
		# (N.B. The description field is not from IB TWS. It is defined
		#  locally in forex.rb, and is just arbitrary text.)
        ib.subscribe(:TickPrice, :TickSize, :TickOption, :TickString) do |msg|
		  what = @market[msg.ticker_id].description || @market[msg.ticker_id].osi
		  puts "#{msg.ticker_id}: #{what}: #{msg.to_human}"
		end

		# Now we actually request market data for the symbols we're interested in.
		@market.each_pair do |id, contract|
		  ib.send_message :RequestMarketData, :ticker_id => id, :contract => contract
		end

		puts "\nSubscribed to market data"
		puts "\n******** Press <Enter> to cancel... *********\n\n"
		STDIN.gets
		puts "Cancelling market data subscription.."

		@market.each_pair { |id, contract| ib.send_message :CancelMarketData, :id => id }
		
    end	



    private

    def fetch_historical_data contract
    	contract_id = contract['id']
    	contract = contract.delete_if{|k,v| k == 'id'}

    	@contracts = {123 => IB::Contract.new(contract)}
        
        client_id = generate_unique_client_id

        ib =  IB::Connection.new :client_id => client_id
        
        ib.subscribe(:Alert) { |msg| puts msg.to_human }

		ib.subscribe(IB::Messages::Incoming::HistoricalData) do |msg|
		   msg.results.each { |entry|
		   	entry.ib_contract_id = contract_id
			puts entry.save
		}
		  @last_msg_time = Time.now.to_i
		end
		
		@contracts.each_pair do |request_id, contract|
			ib.send_message IB::Messages::Outgoing::RequestHistoricalData.new(
		                      :request_id => request_id,
		                      :contract => contract,
		                      :end_date_time => Time.now.to_ib,
		                      :duration => '30 D', # ?
		                      :bar_size => '1 hour', # IB::BAR_SIZES.key(:hour)?
		                      :what_to_show => :trades,
		                      :use_rth => 1,
		                      :format_date => 1)
		end
		sleep 0.1 until @last_msg_time && @last_msg_time < Time.now.to_i + 0.5
	end

    def generate_unique_client_id 
      unique_client_id = nil	
      while true do
        unique_client_id = rand(1000 .. 9999)
        break  unless UniqueClientId.find_by_client_id(unique_client_id).present?
      end 
      UniqueClientId.create(client_id: unique_client_id)
      unique_client_id 
    end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/historical_helper.rb
module HistoricalHelper
end

app/helpers/ib_contracts_helper.rb
module IbContractsHelper
end

app/helpers/ibdata_helper.rb
module IbdataHelper
end

app/views/historical/index.html.erb
<% @contracts.each do |contract| %>
  <h1><%= contract.symbol %></h1></br>
  <%= contract.ib_bars %>
<% end %>

app/views/historical/show.html.erb
<%= @contract.ib_bars %>

app/views/ib_contracts/_form.html.erb
<div class="row">
	<div class='col-md-3 align_center'>
		<h4>Contract Form</h4>
		<%= form_for @contract do |f| %>
		  <div class="form-group">
			  <label class= "control-label" > Con Id</label>
			  <%= f.text_field :con_id, class: 'form-control'%>
		  </div>
		  <div class="form-group">	  
			<%= f.label :sec_type, class: "control-label" %>
			<%= f.text_field :sec_type, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		    <%= f.label :strike, class: "control-label" %>
		    <%= f.text_field :strike, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :currency, class: "control-label" %>
		    <%= f.text_field :currency, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :legs_description, class: "control-label" %>
		    <%= f.text_field :legs_description, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :symbol, class: "control-label" %>
		    <%= f.text_field :symbol, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :local_symbol, class: "control-label" %>
		    <%= f.text_field :local_symbol, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :multiplier, class: "control-label" %>
		    <%= f.text_field :multiplier, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :expiry, class: "control-label" %>
		    <%= f.text_field :expiry, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :exchange, class: "control-label" %>
		    <%= f.text_field :exchange, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :primary_exchange, class: "control-label" %>
		    <%= f.text_field :primary_exchange, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :include_expired, class: "control-label" %>
		    <%= f.text_field :include_expired, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :right, class: "control-label" %>
		    <%= f.text_field :right, class: 'form-control' %>
		  </div>
		  <div class="form-group">  
		    <%= f.label :type, class: "control-label" %>
		    <%= f.text_field :type, class: 'form-control' %>
		  </div> 
		  <div class="form-group">  
		  	<% if params[:action] == 'edit' %>
		      <%= f.submit 'Update Contract', class:'btn btn-primary' %>
		    <% else %>
		      <%= f.submit 'Create Contract', class:'btn btn-primary' %>
		    <% end %>  
		  </div>  
		<% end %>
	</div>	
</div>	

app/views/ib_contracts/edit.html.erb
<%= render partial: 'form' %>

app/views/ib_contracts/index.html.erb
<div>
  <%= link_to "Create New Contract", new_ib_contract_path, class: 'btn btn-primary' %>
</div>
<h5> Following are the available contracts </h5>

<table class="table table-striped table-bordered">
  <tr>
  	<th> Con Id </th>
  	<th> sec_type </th>
  	<th> strike </th>
  	<th> currency </th>
  	<th> sec_id_type </th>
  	<th> sec_id </th>
  	<th> legs_description </th>
  	<th> symbol </th>
  	<th> local_symbol </th>
  	<th> multiplier </th>
  	<th> expiry </th>
  	<th> exchange </th>
  	<th> primary_exchange </th>
  	<th> include_expired </th>
  	<th> right </th>
  	<th> type </th>
  </tr>	
  <% @contracts.each do |contract| %>
    <tr>
      	<td> <%= contract.con_id %> </td>
	  	<td> <%= contract.sec_type %> </td>
	  	<td> <%= contract.strike %> </td>
	  	<td> <%= contract.currency %> </td>
	  	<tD> <%= contract.sec_id_type %> </td>
	  	<td> <%= contract.sec_id %> </td>
	  	<td> <%= contract.legs_description %> </td>
	  	<td> <%= contract.symbol %> </td>
	  	<td> <%= contract.local_symbol %> </td>
      <td> <%= contract.multiplier %> </td>
	  	<td> <%= contract.expiry %> </td>
	  	<td> <%= contract.exchange %> </td>
	  	<td> <%= contract.primary_exchange %> </td>
	  	<td> <%= contract.include_expired %> </td>
	  	<td> <%= contract.right %> </td>
	  	<td> <%= contract.type %> </td>
	  	<td> <%= link_to "Edit Contract", edit_ib_contract_path(contract), class: 'btn btn-primary' %> </td>
	  	<td> <%= link_to "Delete Contract", ib_contract_path(contract), method: :delete , class: 'btn btn-danger' %> </td>
      <td> <%= link_to "Fetch historical data", ibdata_historical_data_path(:id => contract) , class: 'btn btn-primary' %> </td>
    </tr>	
  <% end %>
<table>

<!--div>
  <%= link_to "Fetch Data for all Contracts", ibdata_historical_data_for_all_contracts_path, class: 'btn btn-primary' %>
</div-->  

app/views/ib_contracts/new.html.erb
<%= render partial: 'form'%>

app/views/ibdata/historical_data.html.erb
<h1>Please check IbBar data in data base</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IBDATA" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <!--div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">IBDATA</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
      </div>
    </div!-->

    <!--div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        <!--/div-->

        <div class="span9 margin_top">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>